### ISSUE TITLE
 "lanes=* is used for highways, not railways"

### ISSUE THREAD

**Issue by frodrigo** [OpenRailwayMap/OpenRailwayMap#682] opened 2020-02-29 20:46 UTC
Report of https://github.com/osm-fr/osmose-backend/issues/780

"lanes=* is used for highways, not railways" - it suggests an error for a way tagged:
```
disused:railway = tram
highway = tertiary
railway = disused
lanes=2
```

There is a "highway=*" tag so it shouldn't suggest an error.

**Comment by DerDakon** [comment] 2020-02-29 21:43
Duplicate of #660.

**Closed** 2020-02-29 22:01 UTC
