### ISSUE TITLE
Webserver sometimes provides expired certificate

### ISSUE THREAD

**Issue by rwf-rr** [OpenRailwayMap/OpenRailwayMap#871] opened 2024-02-11 22:42 UTC
At times, access to www.openrailwaymap.org fails with an invalid certificate. The certificate is expired. Repeating the request is likely to succeed (using a newer certificate).

The failed request, made on Feb 11, served the following certificate, with `NotAfter: 2024-01-29 2:00 PM`.

```
X509 Certificate:
Version: 3
Serial Number: 04f1c4733a6b42d4720c5dbc42dd93c92a65
Signature Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.11 sha256RSA
    Algorithm Parameters:
    05 00
Issuer:
    CN=R3
    O=Let's Encrypt
    C=US
  Name Hash(sha1): 48dac9a0fb2bd32d4ff0de68d2f567b735f9b3c4
  Name Hash(md5): 0b1ac7de285115241e78aeecda91be88

 NotBefore: 2023-10-31 2:00 PM
 NotAfter: 2024-01-29 2:00 PM

Subject:
    CN=buegelfalte.openrailwaymap.org
  Name Hash(sha1): 5e604466080a6257791033a4a93ebd82f995c048
  Name Hash(md5): dc59bda6de9830b1965a69c8eb125e7e

Public Key Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.1 RSA
    Algorithm Parameters:
    05 00
Public Key Length: 4096 bits
Public Key: UnusedBits = 0
    0000  30 82 02 0a 02 82 02 01  00 dd 06 b7 ea b9 e4 bf
    0010  75 f4 c3 e7 de 1c 34 33  ef 2f 14 57 ba d9 6f 21
    0020  4c 89 55 a7 ee 3b c2 26  7f 26 9e 99 21 d7 92 30
    0030  e2 d7 12 3e 5f 01 fc 45  ef b4 55 80 60 52 3b 72
    0040  c0 b7 60 aa 70 e3 fa de  45 4a 7e da 7c ff 22 6e
    0050  9b ad d4 c9 98 a5 cf 6a  b3 b3 e9 dc af d5 66 a9
    0060  a8 52 cc a0 64 3d 09 ac  43 5f 04 8e a0 9e bb 9e
    0070  eb 2a cc 3a 95 31 7e 68  a5 5f 66 ea 35 22 1e 03
    0080  fa 61 e5 7b f6 6c 8b 96  3d 8f 4d 8e df 71 f1 c8
    0090  d0 5b 5a 14 3d b8 83 ad  09 2d c0 c4 25 cb 71 a2
    00a0  7a df 6c 1e ac 2c ae 40  80 a4 70 02 bb 6b d6 4b
    00b0  35 51 00 2e 4a 34 0d 22  fe 83 f2 98 14 8d ca 11
    00c0  bd f3 47 0a a8 ce b8 3c  6b 84 af 30 a9 e4 6a ef
    00d0  fd ad db 0f 80 60 eb 0d  06 e6 ab 42 68 51 51 fd
    00e0  7b 99 14 6b d2 df 7d 83  9c f8 dc 83 a8 88 c1 ae
    00f0  78 66 b7 a3 fd ea 61 55  9b d3 cf 73 48 cf d0 f0
    0100  89 b0 12 7f b8 3a 15 e1  e6 9a 82 57 9f 86 60 6c
    0110  9b 89 df 51 71 84 83 2f  6f 2f 7a 4f 7a b4 06 0a
    0120  14 c7 c8 7b 81 f5 6b 26  b4 d6 8f 52 d7 62 0e f1
    0130  f9 fd e4 97 5b 48 b5 24  de dd a3 d6 45 04 fe 05
    0140  37 45 83 db f3 fd 4e 4e  42 92 21 65 97 54 c6 79
    0150  45 82 73 06 da 0e 5f c5  75 fd 4f 67 95 74 ce 87
    0160  b0 5c 51 c3 aa 98 42 68  f9 be 99 e0 8d 8b a0 31
    0170  76 0a e6 a2 e9 29 19 59  74 17 32 32 cd 33 5f 78
    0180  17 ec 23 a1 f4 65 08 ff  8c 98 3e 71 8a 5b 66 87
    0190  64 19 20 fa 4a 47 34 08  ce f8 eb f0 e0 9f 96 98
    01a0  05 e8 54 b9 b6 d4 02 c9  b5 23 69 2f 9d 5e 68 69
    01b0  0e d4 e1 ee d4 64 36 1d  44 60 22 64 ca f0 82 88
    01c0  6e ff 25 ff 78 0a c2 09  48 14 b5 d3 68 8e 6e 18
    01d0  bc 3f ba 70 31 05 0f 23  bb 46 04 f4 34 6f 6f 58
    01e0  f0 5e c2 5b 7c bf b4 20  e2 79 e2 9a b7 e9 de 56
    01f0  a5 96 3f bc b3 ed c2 1e  29 58 a9 35 16 a3 99 92
    0200  94 61 d8 22 5b 17 a5 d7  f7 02 03 01 00 01
Certificate Extensions: 9
    2.5.29.15: Flags = 1(Critical), Length = 4
    Key Usage
        Digital Signature, Key Encipherment (a0)

    2.5.29.37: Flags = 0, Length = 16
    Enhanced Key Usage
        Server Authentication (1.3.6.1.5.5.7.3.1)
        Client Authentication (1.3.6.1.5.5.7.3.2)

    2.5.29.19: Flags = 1(Critical), Length = 2
    Basic Constraints
        Subject Type=End Entity
        Path Length Constraint=None

    2.5.29.14: Flags = 0, Length = 16
    Subject Key Identifier
        67e0e0eb5ebc4363f875e43f6401cc5d7f3650ab

    2.5.29.35: Flags = 0, Length = 18
    Authority Key Identifier
        KeyID=142eb317b75856cbae500940e61faf9d8b14c2c6

    1.3.6.1.5.5.7.1.1: Flags = 0, Length = 49
    Authority Information Access
        [1]Authority Info Access
             Access Method=On-line Certificate Status Protocol (1.3.6.1.5.5.7.48.1)
             Alternative Name:
                  URL=http://r3.o.lencr.org
        [2]Authority Info Access
             Access Method=Certification Authority Issuer (1.3.6.1.5.5.7.48.2)
             Alternative Name:
                  URL=http://r3.i.lencr.org/

    2.5.29.17: Flags = 0, Length = 109
    Subject Alternative Name
        DNS Name=a.tiles.openrailwaymap.org
        DNS Name=api.openrailwaymap.org
        DNS Name=b.tiles.openrailwaymap.org
        DNS Name=blog.openrailwaymap.org
        DNS Name=buegelfalte.openrailwaymap.org
        DNS Name=c.tiles.openrailwaymap.org
        DNS Name=lists.openrailwaymap.org
        DNS Name=openrailwaymap.org
        DNS Name=tiles.openrailwaymap.org
        DNS Name=www.openrailwaymap.org

    2.5.29.32: Flags = 0, Length = c
    Certificate Policies
        [1]Certificate Policy:
             Policy Identifier=2.23.140.1.2.1

    1.3.6.1.4.1.11129.2.4.2: Flags = 0, Length = f4
    SCT List
        v1
        dab6bf6b3fb5b6229f9bc2bb5c6be87091716cbb51848534bda43d3048d7fbab
        October 31, 2023 3:00:56 PM
        SHA256
        ECDSA
        3044022036670b1df9a1c2b31ec0412597fda5c4630ea7ea74567492aefa89857624edd0022048a4b25e01c009a1e00b5cff38bfff258489f1c3b8021f1683843be01c6c6d1c

        v1
        3b5377753e2db9804e8b305b06fe403b67d84fc3f4c7bd000d2d726fe1fad417
        October 31, 2023 3:00:56 PM
        SHA256
        ECDSA
        304502210084cff34e61f3a98303362cf88b9778ea523093a7250959f193d22f9006f2de91022076b52f872c14544a69a728537accda0d3bceb1384a35f7e5f57f2d3236f51396
    CT[0]:
      Version: 1
      Key Id Hash(log-sha256): 2ra/az+1tiKfm8K7XGvocJFxbLtRhIU0vaQ9MEjX+6s=
      Key Id Hash(log-sha256-hex): dab6bf6b3fb5b6229f9bc2bb5c6be87091716cbb51848534bda43d3048d7fbab
      Signing Time: 2023-10-31 3:00 PM
      Extensions: 0000
      Hash Algorithm: 4 (SHA256)
      Signature Algorithm: 3 (ECDSA)
      Length: 0046
0000: 30 44                                     ; SEQUENCE (44 Bytes)
0002:    02 20                                  ; INTEGER (20 Bytes)
0004:    |  36 67 0b 1d f9 a1 c2 b3  1e c0 41 25 97 fd a5 c4
0014:    |  63 0e a7 ea 74 56 74 92  ae fa 89 85 76 24 ed d0
0024:    02 20                                  ; INTEGER (20 Bytes)
0026:       48 a4 b2 5e 01 c0 09 a1  e0 0b 5c ff 38 bf ff 25
0036:       84 89 f1 c3 b8 02 1f 16  83 84 3b e0 1c 6c 6d 1c
    Not found: 2ra/az+1tiKfm8K7XGvocJFxbLtRhIU0vaQ9MEjX+6s=
    CT[1]:
      Version: 1
      Key Id Hash(log-sha256): O1N3dT4tuYBOizBbBv5AO2fYT8P0x70ADS1yb+H61Bc=
      Key Id Hash(log-sha256-hex): 3b5377753e2db9804e8b305b06fe403b67d84fc3f4c7bd000d2d726fe1fad417
      Signing Time: 2023-10-31 3:00 PM
      Extensions: 0000
      Hash Algorithm: 4 (SHA256)
      Signature Algorithm: 3 (ECDSA)
      Length: 0047
0000: 30 45                                     ; SEQUENCE (45 Bytes)
0002:    02 21                                  ; INTEGER (21 Bytes)
0004:    |  00
0005:    |  84 cf f3 4e 61 f3 a9 83  03 36 2c f8 8b 97 78 ea
0015:    |  52 30 93 a7 25 09 59 f1  93 d2 2f 90 06 f2 de 91
0025:    02 20                                  ; INTEGER (20 Bytes)
0027:       76 b5 2f 87 2c 14 54 4a  69 a7 28 53 7a cc da 0d
0037:       3b ce b1 38 4a 35 f7 e5  f5 7f 2d 32 36 f5 13 96
    Not found: O1N3dT4tuYBOizBbBv5AO2fYT8P0x70ADS1yb+H61Bc=

Signature Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.11 sha256RSA
    Algorithm Parameters:
    05 00
Signature: UnusedBits=0
    0000  86 0f 57 bf 95 9a 5c 28  52 ff 43 bc d7 ec e2 63
    0010  fb 61 eb 33 39 59 8b 8b  96 d4 db 17 6f 70 56 29
    0020  48 f5 e5 58 72 d4 1f 91  d9 0a 06 a0 17 02 7e 1f
    0030  fe c2 a6 b4 96 c7 83 70  60 68 2d 3d 35 6c ad 1c
    0040  37 c0 9d 5d 4f 29 53 af  fc 28 88 35 1c 35 cb 6f
    0050  03 dd 5b 16 a8 07 92 3b  3a 0b 68 a9 e0 38 f0 f4
    0060  31 f3 27 0c 57 28 e3 d9  42 bd 7c 05 ce 54 e7 41
    0070  4b e3 69 29 41 e9 d8 e6  f0 9f b1 81 84 a7 fd b4
    0080  27 24 cb a4 f2 8b 8a 86  e9 7b 90 ad ca 95 7d 19
    0090  b5 3b 29 ef a0 be 9b 05  36 9e a6 b7 ca cf a6 6e
    00a0  60 08 77 a2 99 09 1f 48  7d c0 2a 58 e0 cd d6 cb
    00b0  84 14 f6 a0 74 0a 07 43  d4 ff 61 bc fe 5b f6 e1
    00c0  dc 1f 8f ff aa 2b f9 d7  ae f5 22 42 20 1f 57 74
    00d0  ce da 8c cc 14 d4 26 31  87 2d 6c 4a ed b7 00 06
    00e0  cd f1 11 df fa 21 a6 e9  69 b7 09 2c 10 fb 2e af
    00f0  bd 89 41 a6 80 a8 be 27  a2 21 79 84 9b af 01 48
Non-root Certificate
Key Id Hash(rfc-sha1): 67e0e0eb5ebc4363f875e43f6401cc5d7f3650ab
Key Id Hash(sha1): 8ab6d3167073a124f7f04028a60a6d691efb34a8
Key Id Hash(bcrypt-sha1): 2171ea6a81e4d6f4e9f1f668e867c50eefdf916a
Key Id Hash(bcrypt-sha256): 4233cf1e03b6086d84b029502411e736d960942f86ee7e4439d69e299c0a8009
Key Id Hash(md5): 3e36fde31ab12582306f45ca33c5f5d1
Key Id Hash(sha256): e134b8f1b052b207106debe3aed592ccc1a4ed5ccf9ca427b3a205016af1e9d0
Key Id Hash(pin-sha256): b9E2Wtg7CMGuopltJQ0S/WisnIORXYJN2wf4KdWL6RI=
Key Id Hash(pin-sha256-hex): 6fd1365ad83b08c1aea2996d250d12fd68ac9c83915d824ddb07f829d58be912
Cert Hash(md5): abe6cc62ab5f2b2b044e3ecb33ff276b
Cert Hash(sha1): b0464670126f92131b5b199068fd1579d6fdb855
Cert Hash(sha256): fee518f8f2a8c1a83dccf3179c792d39ab64219af74795df9ff9067fe7f47a49
Signature Hash: a95ce736c7e00ce20516543b26f1eb9b356e95e39f362256fd8abf18aed61e19
```
Repeating the request resulted in a valid certificate (`Expires On:	Tuesday, April 30, 2024 at 3:00:57 PM`).

```
X509 Certificate:
Version: 3
Serial Number: 039cff1572fc70ee48e9bcec0df08bcfccb4
Signature Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.11 sha256RSA
    Algorithm Parameters:
    05 00
Issuer:
    CN=R3
    O=Let's Encrypt
    C=US
  Name Hash(sha1): 48dac9a0fb2bd32d4ff0de68d2f567b735f9b3c4
  Name Hash(md5): 0b1ac7de285115241e78aeecda91be88

 NotBefore: 2024-01-31 2:00 PM
 NotAfter: 2024-04-30 2:00 PM

Subject:
    CN=buegelfalte.openrailwaymap.org
  Name Hash(sha1): 5e604466080a6257791033a4a93ebd82f995c048
  Name Hash(md5): dc59bda6de9830b1965a69c8eb125e7e

Public Key Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.1 RSA
    Algorithm Parameters:
    05 00
Public Key Length: 4096 bits
Public Key: UnusedBits = 0
    0000  30 82 02 0a 02 82 02 01  00 dd 06 b7 ea b9 e4 bf
    ...
```

**Comment by Nakaner** [comment] 2024-02-12 22:20
duplicate of https://github.com/OpenRailwayMap/server-admin/issues/40

**Closed by Nakaner** 2024-02-12 22:20 UTC

**Comment by regs01** [comment] 2024-02-12 22:44
There was indeed some caching issues. It's not related to https://github.com/OpenRailwayMap/server-admin/issues/40, but seem to be gone by now.
