### ISSUE TITLE
Stacked Signals are not rendered correctly

### ISSUE THREAD

**Issue by HerrLevin** [OpenRailwayMap/OpenRailwayMap#651] opened 2019-02-26 20:14 UTC
Stacked signals (e.g. a hp-main signal on top of a vr-distant signal) are only rendered as the main signal. That's also the case with BOStrab-Signals. A good example for this is node 4752492363. This one has a Zs 3 at the top, a HP-signal in the middle and a Vr-Signal at the bottom.

**Comment by DerDakon** [comment] 2019-02-26 20:38
The Zs3 is on the maxspeed layer.

**Comment by HerrLevin** [comment] 2019-02-27 09:28
> The Zs3 is on the maxspeed layer.

I know that, but you cannot see the Vr-Signal if a Hp-Signal is on the same pole. 
You can see that also at node 4752492363.

**Comment by Nakaner** [comment] 2019-02-27 10:59
We decided to render the most important signal only because space is limited on the map.

**Comment by HerrLevin** [comment] 2019-02-27 12:28
Would it be possible to make the signals clickable in order to display further information in a popup, or would this rather not be considered?

But I think this might be the wrong approach for BOStrab-Signals. Here the renderer is apparently also not sure what the most important signal is, because partly F0, F1 or e.g. F2 are displayed, so it is not uniform.

**Comment by Nakaner** [comment] 2019-02-27 13:02
> Would it be possible to make the signals clickable in order to display further information in a popup, or would this rather not be considered?

Patches are welcome. See #328

> But I think this might be the wrong approach for BOStrab-Signals. Here the renderer is apparently also not sure what the most important signal is, because partly F0, F1 or e.g. F2 are displayed, so it is not uniform.

The decision whether F0, F1 or F2 is rendered can be found [here](https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/styles/signals.mapcss#L2019). The general approach is to indicate (in terms of mapper feedback) if signal states have been tagged. If not, the stop signal (F0, Hp 0, …) is rendered. If not, a signal other than "straight ahead at full speed" is perferred leading to Hp 2 > Hp 1 > Hp 0.

I am closing this ticket now because it is not a bug but a limitation of rendered map images in general.

**Closed by Nakaner** 2019-02-27 13:02 UTC
