### ISSUE TITLE
How can i change default color of rail roads from orange to the color of my choice

### ISSUE THREAD

**Issue by zameer21** [OpenRailwayMap/OpenRailwayMap#680] opened 2020-02-04 22:28 UTC
When using tile server
How can i change default color of rail roads from orange to the color of my choice

**Comment by Nakaner** [comment] 2020-02-04 22:44
When you use the tile server in the normal setup, you can't change the colour. It serves raster tiles (small PNG files) which are rendered on the server. Tiles which have been rendered once are cached on the server for future users. Therefore, a change can happen for all users only.

If you want to set up a tile server for your own usage, consider the [Ansible playbooks](https://github.com/OpenRailwayMap/server-admin/tree/master/ansible) (they serve as the setup guide temporarily). The Git repository of the map style can be found at https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS. The colour is set at the top of `standard.mss`.

I am closing this ticket now because it is not a bug.

**Closed by Nakaner** 2020-02-04 22:44 UTC
