### ISSUE TITLE
Render platforms, including refs

### ISSUE THREAD

**Issue by bigbug21** [OpenRailwayMap/OpenRailwayMap#308] opened 2015-08-21 10:08 UTC
It would be somewhat good to actually see the platforms of a station, along with their ref tags. Perhaps, at a later steigt, the height and surface tags might be used for further detailed rendering as well.

**Comment by PeterDRS** [comment] 2015-08-22 16:59
Platforms or Platform_edges?

**Comment by bigbug21** [comment] 2015-08-22 18:04
For a start? Platforms (railway=platforms and/or public_transport=platform)!

**Comment by PeterDRS** [comment] 2015-08-22 18:42
The height is an attribute of the platform_edge, not of the whole platform. It can be different for two platform_edges.

**Comment by DerDakon** [comment] 2020-01-16 16:25
Dupe of #190.

**Closed by DerDakon** 2020-01-16 16:25 UTC
Labels: Rendering
